services:
  app:
    image: recruit-app
    container_name: recruit-app
    restart: unless-stopped
    ports:
      - "3002:3000"       # внешний 3002 → внутренний 3000
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TELEGRAM_WEBHOOK_SECRET: ${TELEGRAM_WEBHOOK_SECRET}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
      NEXT_PUBLIC_TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
    volumes:
      - uploads_data:/app/public/uploads
    extra_hosts:
      # чтобы контейнер мог достучаться до PostgreSQL на хосте
      - "host.docker.internal:host-gateway"
    network_mode: bridge

volumes:
  uploads_data:
