services:
  app:
    image: recruit-app
    build: .
    container_name: recruit-app
    restart: unless-stopped
    ports:
      - "3002:3000"       # внешний 3002 → внутренний 3000
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - uploads_data:/app/public/uploads
    extra_hosts:
      # чтобы контейнер мог достучаться до PostgreSQL на хосте
      - "host.docker.internal:host-gateway"
    network_mode: bridge

volumes:
  uploads_data:
